name: money4
description: A new Flutter application.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"


dependencies:
  url_launcher: ^6.0.3
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  image_picker: ^0.8.0+3
  video_player: ^2.1.15

  http: ^0.13.3
  shared_preferences: ^2.0.7
  webview_flutter: ^2.0.10
  flutter_inappwebview: ^5.3.2
  badges: ^2.0.1
  fluttertoast: ^8.0.8
  flutter_html: ^2.1.1
  crypto: ^3.0.1
  flutter_ip: ^0.1.4
  device_simulator: ^0.9.6
  intl_phone_field: ^1.2.0
  sms_otp_auto_verify: ^1.2.2
  passcode_screen: ^1.2.2+1
  flutter_app_lock: ^2.0.0
  flutter_locker: ^2.0.0
  font_awesome_flutter: ^9.1.0
dev_dependencies:

  flutter_test:
    sdk: flutter
#  dio:
# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  uses-material-design: true

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.



  # To add assets to your application, add an assets section, like this:
  assets:
     - assets/files/test.html
     - assets/images/language.png
     - assets/images/eur.png
     - assets/images/key.png
     - assets/images/faceid.png
     - assets/images/vier.png
     - assets/images/rightsign.png
     - assets/images/vectorgotoregister.png
     - assets/images/badge.png
     - assets/images/bigright.png
     - assets/images/bg_loan.png
     - assets/images/bgloan.png
     - assets/images/up_arrow.png
     - assets/images/down_arrrow.png
     - assets/images/tips.png
     - assets/images/enq.png
     - assets/images/depago.png
     - assets/images/faq.png
     - assets/images/doc.png
     - assets/images/histry.png
     - assets/images/terms.png
     - assets/images/s_s.png
     - assets/images/finger_id.png
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages

  fonts:
    - family: TestDomaineDisplay
      fonts:
        - asset: assets\fonts\TestDomaineDisplay-Black.otf
        - asset: assets\fonts\TestDomaineDisplay-Medium.otf
    - family: SFPRODISPLAY
      fonts:
        - asset: assets\fonts\SFPRODISPLAYREGULAR.OTF
